export type NutritionistType =
  | 'Registered Dietitian'
  | 'Sports Nutritionist'
  | 'Clinical Nutritionist'
  | 'Weight Loss Specialist'
  | 'Holistic Nutritionist'
  | 'Functional Nutritionist'
  | 'Nutritional Therapist'
  | 'Gut Health Specialist'
  | 'Plant-Based Nutritionist'
  | 'Eating Disorder Specialist'
  | 'Child Nutritionist'
  | 'Prenatal Nutritionist'
  | 'Postnatal Nutritionist'
  | 'Online Nutritionist'
  | 'Other';
